"""wellness detail fields and session booking

Revision ID: 083479e3cafa
Revises: 6861ec601467
Create Date: 2026-05-13 12:23:55.587774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '083479e3cafa'
down_revision: Union[str, Sequence[str], None] = '6861ec601467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('program_id', sa.Uuid(), nullable=True))
    op.add_column('bookings', sa.Column('booking_type', sa.Enum('room', 'session', name='bookingtype', native_enum=False, length=20), nullable=False, server_default='room'))
    op.create_index(op.f('ix_bookings_booking_type'), 'bookings', ['booking_type'], unique=False)
    op.create_index(op.f('ix_bookings_program_id'), 'bookings', ['program_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'treatment_programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.add_column('sanatoriums', sa.Column('cancellation_policy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sanatoriums', sa.Column('weekly_schedule', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('treatment_programs', sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('treatment_programs', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('treatment_programs', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('treatment_programs', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('treatment_programs', sa.Column('instructor_name', sa.String(length=255), nullable=True))
    op.add_column('treatment_programs', sa.Column('instructor_bio', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('treatment_programs', sa.Column('group_size_min', sa.Integer(), nullable=True))
    op.add_column('treatment_programs', sa.Column('group_size_max', sa.Integer(), nullable=True))
    op.add_column('treatment_programs', sa.Column('what_to_bring', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('treatment_programs', 'min_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treatment_programs', 'min_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('treatment_programs', 'what_to_bring')
    op.drop_column('treatment_programs', 'group_size_max')
    op.drop_column('treatment_programs', 'group_size_min')
    op.drop_column('treatment_programs', 'instructor_bio')
    op.drop_column('treatment_programs', 'instructor_name')
    op.drop_column('treatment_programs', 'currency')
    op.drop_column('treatment_programs', 'price')
    op.drop_column('treatment_programs', 'duration_minutes')
    op.drop_column('treatment_programs', 'description')
    op.drop_column('sanatoriums', 'weekly_schedule')
    op.drop_column('sanatoriums', 'cancellation_policy')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_program_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_type'), table_name='bookings')
    op.drop_column('bookings', 'booking_type')
    op.drop_column('bookings', 'program_id')
    # ### end Alembic commands ###
