"""create sanatoriums and sanatorium_images tables

Revision ID: 2151a795820b
Revises: d478ab0979a8
Create Date: 2026-05-11 00:39:17.157058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2151a795820b'
down_revision: Union[str, Sequence[str], None] = 'd478ab0979a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanatoriums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='sanatoriumstatus', native_enum=False, length=20), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanatoriums_admin_user_id'), 'sanatoriums', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_sanatoriums_city'), 'sanatoriums', ['city'], unique=False)
    op.create_index(op.f('ix_sanatoriums_name'), 'sanatoriums', ['name'], unique=False)
    op.create_index(op.f('ix_sanatoriums_slug'), 'sanatoriums', ['slug'], unique=True)
    op.create_index(op.f('ix_sanatoriums_status'), 'sanatoriums', ['status'], unique=False)
    op.create_table('sanatorium_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sanatorium_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sanatorium_id'], ['sanatoriums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanatorium_images_sanatorium_id'), 'sanatorium_images', ['sanatorium_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanatorium_images_sanatorium_id'), table_name='sanatorium_images')
    op.drop_table('sanatorium_images')
    op.drop_index(op.f('ix_sanatoriums_status'), table_name='sanatoriums')
    op.drop_index(op.f('ix_sanatoriums_slug'), table_name='sanatoriums')
    op.drop_index(op.f('ix_sanatoriums_name'), table_name='sanatoriums')
    op.drop_index(op.f('ix_sanatoriums_city'), table_name='sanatoriums')
    op.drop_index(op.f('ix_sanatoriums_admin_user_id'), table_name='sanatoriums')
    op.drop_table('sanatoriums')
    # ### end Alembic commands ###
