"""add property_type wellness_category region to sanatoriums

Revision ID: 6861ec601467
Revises: ad5c77a820ed
Create Date: 2026-05-13 12:10:41.101615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6861ec601467'
down_revision: Union[str, Sequence[str], None] = 'ad5c77a820ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanatoriums', sa.Column('region', sa.String(length=120), nullable=True))
    op.add_column('sanatoriums', sa.Column('property_type', sa.Enum('sanatorium', 'wellness', name='propertytype', native_enum=False, length=20), nullable=False, server_default='sanatorium'))
    op.add_column('sanatoriums', sa.Column('wellness_category', sa.Enum('spa_resort', 'yoga_retreat', 'meditation_center', 'fitness_resort', 'beauty_spa', 'digital_detox', name='wellnesscategory', native_enum=False, length=30), nullable=True))
    op.create_index(op.f('ix_sanatoriums_property_type'), 'sanatoriums', ['property_type'], unique=False)
    op.create_index(op.f('ix_sanatoriums_region'), 'sanatoriums', ['region'], unique=False)
    op.create_index(op.f('ix_sanatoriums_wellness_category'), 'sanatoriums', ['wellness_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanatoriums_wellness_category'), table_name='sanatoriums')
    op.drop_index(op.f('ix_sanatoriums_region'), table_name='sanatoriums')
    op.drop_index(op.f('ix_sanatoriums_property_type'), table_name='sanatoriums')
    op.drop_column('sanatoriums', 'wellness_category')
    op.drop_column('sanatoriums', 'property_type')
    op.drop_column('sanatoriums', 'region')
    # ### end Alembic commands ###
