"""add sanatorium contact fields, payment methods, house rules, seasonal pricing

Revision ID: ad5c77a820ed
Revises: c3765ad10e35
Create Date: 2026-05-13 08:06:10.905803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5c77a820ed'
down_revision: Union[str, Sequence[str], None] = 'c3765ad10e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_price_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_category_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_price_weekend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_price_periods_date_from'), 'room_price_periods', ['date_from'], unique=False)
    op.create_index(op.f('ix_room_price_periods_date_to'), 'room_price_periods', ['date_to'], unique=False)
    op.create_index(op.f('ix_room_price_periods_room_category_id'), 'room_price_periods', ['room_category_id'], unique=False)
    op.add_column('sanatoriums', sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('sanatoriums', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('sanatoriums', sa.Column('check_in_time', sa.Time(), nullable=True))
    op.add_column('sanatoriums', sa.Column('check_out_time', sa.Time(), nullable=True))
    op.add_column('sanatoriums', sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('sanatoriums', sa.Column('house_rules', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('sanatoriums', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanatoriums', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('sanatoriums', 'house_rules')
    op.drop_column('sanatoriums', 'payment_methods')
    op.drop_column('sanatoriums', 'check_out_time')
    op.drop_column('sanatoriums', 'check_in_time')
    op.drop_column('sanatoriums', 'website')
    op.drop_column('sanatoriums', 'phones')
    op.drop_index(op.f('ix_room_price_periods_room_category_id'), table_name='room_price_periods')
    op.drop_index(op.f('ix_room_price_periods_date_to'), table_name='room_price_periods')
    op.drop_index(op.f('ix_room_price_periods_date_from'), table_name='room_price_periods')
    op.drop_table('room_price_periods')
    # ### end Alembic commands ###
